version: "3.3"

services:
  app:
    image: drf:latest
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db


  db:
    image: postgres:latest
    command: python manage.py migrate --noinput
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
volumes:
  database-data:
