version: "3.9"

services:
  database:
    image: postgres:latest
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file:
      - database.env
    ports:
      - 5432:5432

volumes:
  database-data:
