# Generated by Django 3.1 on 2021-07-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('news', '0002_news_title'), ('news', '0003_news_text')]

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default=None, max_length=150, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default=None, verbose_name='Новость'),
            preserve_default=False,
        ),
    ]
