# Generated by Django 3.1 on 2021-07-15 01:23

from django.db import migrations
from django.db.migrations import RunPython


def change_data(apps, schema_editor):
    News = apps.get_model('news', 'News')

    news = [
        every_news.title.upper()
        for every_news in News.objects.all()
    ]
    News.objects.bulk_update(news, ['title'])


def change_data_reverse(apps, schema_editor):
    News = apps.get_model('news', 'News')

    news = [
        every_news.title.capitalize()
        for every_news in News.objects.all()
    ]
    News.objects.bulk_update(news, ['title'])


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_title_squashed_0003_news_text'),
    ]

    operations = [
        RunPython(change_data, reverse_code=change_data_reverse)
    ]
